<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dashboard;


class DashboardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dashRecord = [
            ['id'=>2, 'imagePath' => 'x.jpg', 'storeName'=>'Roti Gembong', 'category'=>'Food And Drink', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.19','noWa'=>'+6285604748674', 'ig'=>'rotiGembong','vendorId'=>1],
            ['id'=>3, 'imagePath' => 'x.jpg', 'storeName'=>'Ayo Ngopi', 'category'=>'Food And Drink', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.20','noWa'=>'+6285604748674', 'ig'=>'aoNgopi','vendorId'=>2],
            ['id'=>4, 'imagePath' => 'x.jpg', 'storeName'=>'Klambi Anyar', 'vendorId'=>5, 'category'=>'Clothes', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Afffandi No.32','noWa'=>'+6285604748674', 'ig'=>'klambianyar'],
            ['id'=>7, 'imagePath' => 'x.jpg', 'storeName'=>'Ails Wear','vendorId'=>6, 'category'=>'Clothes', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.209','noWa'=>'+6285604748674', 'ig'=>'ails_wear00'],
            ['id'=>8, 'imagePath' => 'x.jpg', 'storeName'=>'Hijrah Store','category'=>'Clothes', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl.Magelang No.674','noWa'=>'+6285604748674', 'ig'=>'hijrah_store', 'vendorId'=>7],
            ['id'=>9, 'imagePath' => 'x.jpg', 'storeName'=>'PantShoes', 'category'=>'Clothes', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.109','noWa'=>'+6285604748674', 'ig'=>'pantShoes','vendorId'=>8],
            ['id'=>10, 'imagePath' => 'x.jpg', 'storeName'=>'Paint Me', 'category'=>'Art', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Nganklik 09','noWa'=>'+6285604748674', 'ig'=>'PaintMe', 'vendorId'=>9],
            ['id'=>11, 'imagePath' => 'x.jpg', 'storeName'=>'Cat Mu!', 'category'=>'Art', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.199','noWa'=>'+6285604748674', 'ig'=>'cat_Mu','vendorId'=>10],
            ['id'=>12, 'imagePath' => 'x.jpg', 'storeName'=>'Toko Raja', 'category'=>'Furniture', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Selokan Mataram','noWa'=>'+6285604748674', 'ig'=>'rajaToko', 'vendorId'=>11],
            ['id'=>13, 'imagePath' => 'x.jpg', 'storeName'=>'Ini Mable', 'category'=>'Furniture', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Mataram 89','noWa'=>'+6285604748674', 'ig'=>'this_mable','vendorId'=>12],
            ['id'=>14, 'imagePath' => 'x.jpg', 'storeName'=>'ElektroniKita!', 'category'=>'Electronic', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Magelang 87','noWa'=>'+6285604748674', 'ig'=>'elektronik_kita','vendorId'=>13],
            ['id'=>15, 'imagePath' => 'x.jpg', 'storeName'=>'JualHP', 'category'=>'Electronic', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.100','noWa'=>'+6285604748674', 'ig'=>'jual_hp', 'vendorId'=>14],
            ['id'=>16, 'imagePath' => 'x.jpg', 'storeName'=>'Ayo Cantik', 'category'=>'Beauty And Health', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.1099','noWa'=>'+6285604748674', 'ig'=>'ayocantik','vendorId'=>15],
            ['id'=>17, 'imagePath' => 'x.jpg', 'storeName'=>'skincareAn', 'category'=>'Beauty And Health', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Affandi 86','noWa'=>'+6285604748674', 'ig'=>'skincare', 'vendorId'=>16],
            ['id'=>18, 'imagePath' => 'x.jpg', 'storeName'=>'Ayam Gepuk Ailsa', 'category'=>'Food And Drink', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Kaliurang 76','noWa'=>'+6285604748674', 'ig'=>'Gepukailsa','vendorId'=>17],
            ['id'=>19, 'imagePath' => 'x.jpg', 'storeName'=>'Thaitea Oren', 'category'=>'Food And Drink', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Monjali No. 90','noWa'=>'+6285604748674', 'ig'=>'thaitea_oren','vendorId'=>18],
            ['id'=>20, 'imagePath' => 'x.jpg', 'storeName'=>'Angkringan Neng','category'=>'Food And Drink', 'desc'=>'Pretium viverra suspendisse potenti nullam. Maecenas ultricies mi eget mauris pharetra. Nisi scelerisque eu ultrices vitae auctor. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Mattis ullamcorper velit sed ullamcorper. At elementum eu facilisis sed odio. Vulputate sapien nec sagittis aliquam. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ultricies leo integer malesuada nunc. Viverra vitae congue eu consequat ac felis donec et odio. Nisl tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Ipsum suspendisse ultrices gravida dictum fusce ut placerat.', 'address'=>'Jl. Malioboro No.1089','noWa'=>'+6285604748674', 'ig'=>'angkringan_neng','vendorId'=>19]
        ];
        Dashboard::insert($dashRecord);
    }
}
